uploads = []

[[generated]]
id = "_0vd1JqQNVPg8OSEUIlsV"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ePIxWluLRsxaYtKXA6oeF"
uri = "file://attached_assets/trampaj_profile.png"
type = "image"
title = "trampaj profile picture"

[[generated]]
id = "jcIf8VbL_fD24YP8ozSrn"
uri = "file://attached_assets/trampaj_cover.png"
type = "image"
title = "trampaj facebook cover"

[[generated]]
id = "yzf5y28ly0whFj04hM8xg"
uri = "file://attached_assets/trampaj_profile_v2.png"
type = "image"
title = "trampaj logo profile"

[[generated]]
id = "KR0QED25nHSz5aFA9iGVL"
uri = "file://attached_assets/trampaj_cover_v2.png"
type = "image"
title = "trampaj facebook cover v2"

[[outputs]]
id = "BQ3upFCsGN8b0gGwDiP5q"
uri = "file://attached_assets/trampaj_profile.png"
type = "image"
title = "Profilna slika (1:1)"

[[outputs]]
id = "85GrxruIpgK3vgXjoHX6z"
uri = "file://attached_assets/trampaj_cover.png"
type = "image"
title = "Naslovna slika (16:9)"

[[outputs]]
id = "h7MTKDuLEuukSSCW9DKzK"
uri = "file://attached_assets/trampaj_profile_v2.png"
type = "image"
title = "Profilna slika v2"

[[outputs]]
id = "BALYmPd04Y4JtgWjZXcVu"
uri = "file://attached_assets/trampaj_cover_v2.png"
type = "image"
title = "Naslovna slika v2 (tekst desno, lijevo slobodno za profilnu)"

[[outputs]]
id = "C3-rYHOO0erwFGAqBMPvn"
uri = "file://artifacts/api-server/public/trampa.apk.tar.gz"
type = "unspecified"
title = "Trampa.apk (arhiva)"
